version: '3.1'
services:

  ### Nginx container #########################################

  nginx:
      image: lwl12/lfs-nginx
      container_name: nginx
      env_file: .env
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - /data/wwwroot:/data/wwwroot:rw
        - /data/wwwlogs:/data/wwwlogs:rw
        - /opt/ssl:/opt/ssl:ro
      restart: always
      hostname: ${Hostname}
      networks:
        - net-lfs
      environment:
        TZ: ${TZ}
      secrets:
        - lwl12.com.key
        - cn2.network.key
        - lwl.moe.key
        - lwl12.com.cer
        - cn2.network.cer
        - lwl.moe.cer
        - lwl12.com_ecc.key
        - cn2.network_ecc.key
        - lwl.moe_ecc.key
        - lwl12.com_ecc.cer
        - cn2.network_ecc.cer
        - lwl.moe_ecc.cer
        - letsencrypt.ca.cer
      deploy:
        mode: global
      

  ### PHP container #########################################
  php:
      image: lwl12/lfs-php
      container_name: php
      env_file: .env
      expose:
        - "9000"
      volumes:
        - /data/wwwroot:/data/wwwroot:rw
        - /var/log/php:/var/log:rw
      restart: always
      networks:
        - net-lfs
      environment:
        TZ: ${TZ}
      deploy:
        mode: global

  ### Mysql container #########################################

  mysql:
      image: mysql:8.0
      container_name: mysql
      expose:
        - "3306"
      volumes:
        - /data/mysql:/var/lib/mysql:rw
        #- ./config/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
        - /var/log/mysql:/var/log/mysql:rw
      restart: always
      environment:
        TZ: ${TZ}
        MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      secrets:
        - mysql_root_password
      networks:
        - net-lfs
      deploy:
        mode: global

  ### Redis container #########################################

  redis:
      image: redis:4-alpine
      container_name: redis
      env_file: .env
      expose:
        - "6379"
      volumes:
        - ./config/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
        - /var/log/redis/redis.log:/var/log/redis/redis.log:rw
      restart: always
      environment:
        TZ: ${TZ}
      networks:
        - net-lfs
      deploy:
        mode: global

secrets:
  mysql_root_password:
    file: ./mysql_root_password.txt
  lwl12.com.key:
    file: /opt/ssl/lwl12.com.key
  cn2.network.key:
    file: /opt/ssl/lwl12.com.key
  lwl.moe.key:
    file: /opt/ssl/lwl12.com.key
  lwl12.com.cer:
    file: /opt/ssl/lwl12.com.cer
  cn2.network.cer:
    file: /opt/ssl/lwl12.com.cer
  lwl.moe.cer:
    file: /opt/ssl/lwl12.com.cer
  lwl12.com_ecc.key:
    file: /opt/ssl/lwl12.com_ecc.key
  cn2.network_ecc.key:
    file: /opt/ssl/lwl12.com_ecc.key
  lwl.moe_ecc.key:
    file: /opt/ssl/lwl12.com_ecc.key
  lwl12.com_ecc.cer:
    file: /opt/ssl/lwl12.com_ecc.cer
  cn2.network_ecc.cer:
    file: /opt/ssl/lwl12.com_ecc.cer
  lwl.moe_ecc.cer:
    file: /opt/ssl/lwl12.com_ecc.cer
  letsencrypt.ca.cer:
    file: /opt/ssl/letsencrypt.ca.cer

networks:
  net-lfs: